% readStakes.m

% read in the stakes data from 'allStakes_timeSeries_X' and save it out to
% a *.mat file

% Ian Raphael
% ian.th@dartmouth.edu
% 2021.03.09

close all
clear

cd("/Users/"+getenv('USER')+"/Desktop/Stakes")

addpath(genpath(pwd));

filePath = "/Users/f001ymh/Desktop/Stakes/1. Data/2. Preprocessed Data/allStakes_timeSeries_QAd_2021.04.09.csv";

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/f001ymh/Desktop/Stakes/1. Data/allStakes_timeSeries_cleaned_3.csv
%
% Auto-generated by MATLAB on 09-Mar-2021 13:27:47

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 19);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["SiteName", "StakeID", "StakeName", "DateInstalled", "DateofLastMeasurement", "InitialIceThickness", "InitialDraft", "MeasurementDate", "ThicknessGaugeMeasurement", "IceSurfaceMeasurement", "SnowSurfaceMeasurement", "SnowThickness", "DrilledIceThickness", "Ponded", "Comments","iceAge","QATop","QABottom","qaComments"];
opts.VariableTypes = ["string", "double", "string", "datetime", "datetime", "double", "double", "datetime", "double", "double", "double", "double", "double", "double", "string","double","double","double","string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["SiteName", "StakeName", "Comments","qaComments"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["SiteName", "StakeName", "Comments","qaComments"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "DateInstalled", "InputFormat", "yyyy.MM.dd");
opts = setvaropts(opts, "DateofLastMeasurement", "InputFormat", "yyyy.MM.dd");
opts = setvaropts(opts, "MeasurementDate", "InputFormat", "yyyy.MM.dd");
opts = setvaropts(opts, "Ponded", "TrimNonNumeric", true);
opts = setvaropts(opts, "Ponded", "ThousandsSeparator", ",");

% Import the data
tbl = readtable(filePath, opts);

%% Convert to output type


allStakes.siteName = tbl.SiteName;
allStakes.stakeID = tbl.StakeID;
allStakes.stakeName = tbl.StakeName;
allStakes.dateInstalled = tbl.DateInstalled;
allStakes.dateOfLastMeasurement = tbl.DateofLastMeasurement;
allStakes.initialIceThickness = tbl.InitialIceThickness;
allStakes.initialDraft = tbl.InitialDraft;
allStakes.measurementDate = tbl.MeasurementDate;
allStakes.thicknessGaugeMeasurement = tbl.ThicknessGaugeMeasurement;
allStakes.iceSurfaceMeasurement = tbl.IceSurfaceMeasurement;
allStakes.snowSurfaceMeasurement = tbl.SnowSurfaceMeasurement;
allStakes.snowThickness = tbl.SnowThickness;
allStakes.drilledIceThickness = tbl.DrilledIceThickness;
allStakes.pondFlag= tbl.Ponded;
allStakes.comments = tbl.Comments;
allStakes.qaComments = tbl.qaComments;
allStakes.purgeTop = tbl.QATop;
allStakes.purgeBottom = tbl.QABottom;
allStakes.iceAge = tbl.iceAge;


%% Clear temporary variables
clear opts tbl

save("./1. Data/2. Preprocessed Data/allStakes_timeSeries_QAd_"+string(date),'allStakes');